**2.Normalization:-** Normalization is a feature scaling technique where the values of a dataset are rescaled to a fixed range for all the columns(features) data.

**There are major 4 types of normalization** 1.Min-Max Scaling[0,1]  ----------------  2.Mean Normalization [-1,1] -----------------3.Max Absolute scaling[-1,1]  ------------------ 4.Robust Sacling

**1.Min-Max Scaling :- Xi = (Xi - Xmin)/(Xmax-Xmin)**

In [19]:
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

In [20]:
df = pd.read_csv('salary_prediction_data.csv')
df

       Education  Experience  Location Job_Title  Age  Gender         Salary
0    High School           8     Urban   Manager   63    Male   84620.053665
1            PhD          11  Suburban  Director   59    Male  142591.255894
2       Bachelor          28  Suburban   Manager   61  Female   97800.255404
3    High School          29     Rural  Director   45    Male   96834.671282
4            PhD          25     Urban   Analyst   26  Female  132157.786175
..           ...         ...       ...       ...  ...     ...            ...
995  High School           8  Suburban   Analyst   25  Female   64683.389864
996  High School          24     Urban  Engineer   30  Female   74468.205020
997       Master          18     Rural   Analyst   44    Male   98207.026024
998     Bachelor          27  Suburban  Director   31  Female  108544.922720
999  High School          25     Urban  Director   41  Female   71077.000066

[1000 rows x 7 columns]

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Education   1000 non-null   object
 1   Experience  1000 non-null   int64
 2   Location    1000 non-null   object
 3   Job_Title   1000 non-null   object
 4   Age         1000 non-null   int64
 5   Gender      1000 non-null   object
 6   Salary      1000 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 54.8+ KB

In [22]:
df.drop(['Education','Location','Job_Title','Gender'],axis=1,inplace=True)

In [23]:
df

     Experience  Age         Salary
0             8   63   84620.053665
1            11   59  142591.255894
2            28   61   97800.255404
3            29   45   96834.671282
4            25   26  132157.786175
..          ...  ...            ...
995           8   25   64683.389864
996          24   30   74468.205020
997          18   44   98207.026024
998          27   31  108544.922720
999          25   41   71077.000066

[1000 rows x 3 columns]

In [24]:
# now we split or data into train and test 
from sklearn.model_selection import train_test_split

In [25]:
X_train , X_test = train_test_split(df,test_size=0.2,random_state=42)

In [26]:
X_train

     Experience  Age         Salary
29           14   61   75559.244114
535           7   21   85397.137796
695          11   22  112787.349256
557           4   60  107455.134948
836          17   63  108464.320139
..          ...  ...            ...
106          27   21   66723.680518
270           7   22   62891.766866
860           2   26  107445.343659
435           1   39   52716.988933
102           5   22   91289.995875

[800 rows x 3 columns]

In [27]:
X_test

     Experience  Age         Salary
521          13   57   86677.840109
737           6   59   56036.163010
740          16   61   92226.871819
660           5   26  100710.088052
411          26   27   91775.012832
..          ...  ...            ...
408           2   22   62915.445683
332          27   58   92041.749991
208          15   54   85534.397486
613          24   63  164373.967469
78            5   26   93375.479141

[200 rows x 3 columns]

**AAM ZINDAGI**

In [33]:
Age_min = np.min(df['Age'])
Age_max = np.max(df['Age'])
Salary_min = np.min(df['Salary'])
Salary_max = np.max(df['Salary'])
experience_min = np.min(df['Experience'])
experience_max = np.max(df['Experience'])

In [34]:
Age_min

np.int64(20)

In [41]:
df_scaled = pd.DataFrame()

In [42]:
df_scaled['Age_Scaling'] = (df['Age'] -Age_min)/(Age_max-Age_min)

In [43]:
df_scaled['Salary_Sacaling'] = (df['Salary'] -Salary_min)/(Salary_max-Salary_min)

In [44]:
df_scaled['Experience_Scaling'] = (df['Experience'] - experience_min)/(experience_max-experience_min)

In [45]:
df_scaled

     Age_Scaling  Salary_Sacaling  Experience_Scaling
0       0.977273         0.320424            0.250000
1       0.886364         0.683866            0.357143
2       0.931818         0.403055            0.964286
3       0.568182         0.397002            1.000000
4       0.136364         0.618455            0.857143
..           ...              ...                 ...
995     0.113636         0.195434            0.250000
996     0.227273         0.256778            0.821429
997     0.545455         0.405605            0.607143
998     0.250000         0.470417            0.928571
999     0.477273         0.235518            0.857143

[1000 rows x 3 columns]

In [48]:
print("Before Scaling")
df.drop(['Experience_Scaling','Salary_Sacaling','Age_Scaling'],inplace=True,axis = 1)
df

Before Scaling

     Experience  Age         Salary
0             8   63   84620.053665
1            11   59  142591.255894
2            28   61   97800.255404
3            29   45   96834.671282
4            25   26  132157.786175
..          ...  ...            ...
995           8   25   64683.389864
996          24   30   74468.205020
997          18   44   98207.026024
998          27   31  108544.922720
999          25   41   71077.000066

[1000 rows x 3 columns]

In [50]:
print("After Scaling")
df_scaled

After Scaling

     Age_Scaling  Salary_Sacaling  Experience_Scaling
0       0.977273         0.320424            0.250000
1       0.886364         0.683866            0.357143
2       0.931818         0.403055            0.964286
3       0.568182         0.397002            1.000000
4       0.136364         0.618455            0.857143
..           ...              ...                 ...
995     0.113636         0.195434            0.250000
996     0.227273         0.256778            0.821429
997     0.545455         0.405605            0.607143
998     0.250000         0.470417            0.928571
999     0.477273         0.235518            0.857143

[1000 rows x 3 columns]

**MENTOS ZINDAGI**

In [51]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [52]:
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [53]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [55]:
X_train_scaled

     Experience       Age    Salary
0      0.464286  0.931818  0.263618
1      0.214286  0.022727  0.325296
2      0.357143  0.045455  0.497014
3      0.107143  0.909091  0.463585
4      0.571429  0.977273  0.469912
..          ...       ...       ...
795    0.928571  0.022727  0.208225
796    0.214286  0.045455  0.184201
797    0.035714  0.136364  0.463524
798    0.000000  0.431818  0.120412
799    0.142857  0.045455  0.362240

[800 rows x 3 columns]

In [54]:
np.round(X_train_scaled.describe(),1)

       Experience    Age  Salary
count       800.0  800.0   800.0
mean          0.5    0.5     0.5
std           0.3    0.3     0.2
min           0.0    0.0     0.0
25%           0.2    0.2     0.3
50%           0.5    0.5     0.4
75%           0.8    0.8     0.6
max           1.0    1.0     1.0

**2.Mean Normalization**
**AAM ZINDAGI**

In [ ]:
df

     Experience  Age         Salary
0             8   63   84620.053665
1            11   59  142591.255894
2            28   61   97800.255404
3            29   45   96834.671282
4            25   26  132157.786175
..          ...  ...            ...
995           8   25   64683.389864
996          24   30   74468.205020
997          18   44   98207.026024
998          27   31  108544.922720
999          25   41   71077.000066

[1000 rows x 3 columns]

In [58]:
Age_mean = np.mean(df['Age'])
salary_mean = np.mean(df['Salary'])
Experience_mean = np.mean(df['Experience'])

In [59]:
df_mean_scaled = pd.DataFrame()
df_mean_scaled['Age_mean_Scaled'] = (df['Age'] - Age_mean )/(Age_max -Age_mean)
df_mean_scaled['Salary_mean_Scaled'] = (df['Salary'] -salary_mean) /(Salary_max-salary_mean)
df_mean_scaled['Experience_mean_Scaled'] = (df['Experience']-Experience_mean)/(experience_max-Experience_mean)

In [61]:
df_mean_scaled

     Age_mean_Scaled  Salary_mean_Scaled  Experience_mean_Scaled
0           0.953753           -0.239410               -0.475859
1           0.768765            0.423435               -0.265022
2           0.861259           -0.088707                0.929721
3           0.121306           -0.099747                1.000000
4          -0.757388            0.304138                0.718884
..               ...                 ...                     ...
995        -0.803635           -0.467366               -0.475859
996        -0.572400           -0.355486                0.648605
997         0.075059           -0.084056                0.226931
998        -0.526153            0.034148                0.859442
999        -0.063682           -0.394262                0.718884

[1000 rows x 3 columns]

There is no class  present in the sklearn for Mean Normalization like MinMax Scalar

**3.Max Absolute Scaling :- Xi = Xi / |Xmax|** ------------------It is used when we have sparse data(Maximum values are zero)------------------------AAM ZINDAGI

In [62]:
df

     Experience  Age         Salary
0             8   63   84620.053665
1            11   59  142591.255894
2            28   61   97800.255404
3            29   45   96834.671282
4            25   26  132157.786175
..          ...  ...            ...
995           8   25   64683.389864
996          24   30   74468.205020
997          18   44   98207.026024
998          27   31  108544.922720
999          25   41   71077.000066

[1000 rows x 3 columns]

In [65]:
df_abs_scaled = pd.DataFrame()

In [66]:
df_abs_scaled['Experience_abs'] = df['Experience'] / experience_max 
df_abs_scaled['Age_abs'] = df['Age'] / Age_max
df_abs_scaled['Salary_abs'] = df['Salary'] / Salary_max

In [67]:
df_abs_scaled

     Experience_abs   Age_abs  Salary_abs
0          0.275862  0.984375    0.438408
1          0.379310  0.921875    0.738751
2          0.965517  0.953125    0.506693
3          1.000000  0.703125    0.501691
4          0.862069  0.406250    0.684696
..              ...       ...         ...
995        0.275862  0.390625    0.335118
996        0.827586  0.468750    0.385812
997        0.620690  0.687500    0.508801
998        0.931034  0.484375    0.562361
999        0.862069  0.640625    0.368243

[1000 rows x 3 columns]

**MENTOS ZINDAGI**

In [68]:
from sklearn.preprocessing import MaxAbsScaler

In [69]:
MAS = MaxAbsScaler()

In [70]:
df_abs_scaled2 = MAS.fit_transform(df)

In [71]:
df_abs_scaled2

array([[0.27586207, 0.984375  , 0.43840816],
       [0.37931034, 0.921875  , 0.73875125],
       [0.96551724, 0.953125  , 0.50669349],
       ...,
       [0.62068966, 0.6875    , 0.50880093],
       [0.93103448, 0.484375  , 0.56236055],
       [0.86206897, 0.640625  , 0.36824293]], shape=(1000, 3))

In [74]:
df_abs_scaled2 = pd.DataFrame(df_abs_scaled2,columns=df.columns)

In [75]:
df_abs_scaled2

     Experience       Age    Salary
0      0.275862  0.984375  0.438408
1      0.379310  0.921875  0.738751
2      0.965517  0.953125  0.506693
3      1.000000  0.703125  0.501691
4      0.862069  0.406250  0.684696
..          ...       ...       ...
995    0.275862  0.390625  0.335118
996    0.827586  0.468750  0.385812
997    0.620690  0.687500  0.508801
998    0.931034  0.484375  0.562361
999    0.862069  0.640625  0.368243

[1000 rows x 3 columns]

In [76]:
df_abs_scaled

     Experience_abs   Age_abs  Salary_abs
0          0.275862  0.984375    0.438408
1          0.379310  0.921875    0.738751
2          0.965517  0.953125    0.506693
3          1.000000  0.703125    0.501691
4          0.862069  0.406250    0.684696
..              ...       ...         ...
995        0.275862  0.390625    0.335118
996        0.827586  0.468750    0.385812
997        0.620690  0.687500    0.508801
998        0.931034  0.484375    0.562361
999        0.862069  0.640625    0.368243

[1000 rows x 3 columns]

**4.Robust Scaling** :- it is used onl if we have lots of outliers present in the data

In [77]:
from sklearn.preprocessing import RobustScaler

In [79]:
RS = RobustScaler()
df_robust_scaled = RS.fit_transform(df)

In [80]:
df_robust_scaled

array([[-0.46666667,  0.8       , -0.47147632],
       [-0.26666667,  0.64      ,  0.91632729],
       [ 0.86666667,  0.72      , -0.15594842],
       ...,
       [ 0.2       ,  0.04      , -0.14621052],
       [ 0.8       , -0.48      ,  0.10127391],
       [ 0.66666667, -0.08      , -0.79569073]], shape=(1000, 3))

In [81]:
df_robust_scaled = pd.DataFrame(df_robust_scaled,columns=df.columns)

In [82]:
df_robust_scaled

     Experience   Age    Salary
0     -0.466667  0.80 -0.471476
1     -0.266667  0.64  0.916327
2      0.866667  0.72 -0.155948
3      0.933333  0.08 -0.179064
4      0.666667 -0.68  0.666555
..          ...   ...       ...
995   -0.466667 -0.72 -0.948751
996    0.600000 -0.52 -0.714507
997    0.200000  0.04 -0.146211
998    0.800000 -0.48  0.101274
999    0.666667 -0.08 -0.795691

[1000 rows x 3 columns]