In [1]:
!pip show numpy

WARNING: Package(s) not found: numpy

In [2]:
!pip show pandas

WARNING: Package(s) not found: pandas

In [3]:
!pip install numpy

Collecting numpy
  Downloading numpy-2.4.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Downloading numpy-2.4.2-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.3 MB 3.4 MB/s eta 0:00:04
   ----- ---------------------------------- 1.6/12.3 MB 3.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.3 MB 4.3 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.3 MB 4.4 MB/s eta 0:00:02
   ---------------- ----------------------- 5.0/12.3 MB 4.6 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.3 MB 4.8 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.3 MB 5.2 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.3 MB 5.5 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.3 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 5.8 MB/s  0:00:02
Installing collected packages: numpy
Successfully installed numpy-2.4.2

In [4]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.0-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\shiva\anaconda3\envs\mllearning\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shiva\anaconda3\envs\mllearning\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\shiva\anaconda3\envs\mllearning\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp313-cp313-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.7 MB 6.0 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.7 MB 5.1 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/9.7 MB 4.8 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.7 MB 5.0 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.7 MB 5.1 MB/s eta 0:00:01
   ---------------------------- ----------- 6.8/9.7 MB 5.2 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.7 MB 5.2 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 5.1 MB/s  0:00:02
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.0 tzdata-2025.3

In [5]:
!pip show numpy

Name: numpy
Version: 2.4.2
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License-Expression: BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0
Location: C:\Users\shiva\anaconda3\envs\MLLearning\Lib\site-packages
Requires:
Required-by: pandas

In [6]:
!pip show pandas

Name: pandas
Version: 3.0.0
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

 Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
 All rights reserved.

 Copyright (c) 2011-2026, Open source contributors.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Location: C:\Users\shiva\anaconda3\envs\MLLearning\Lib\site-packages
Requires: numpy, python-dateutil, tzdata
Required-by:

In [7]:
import numpy as np

In [1]:
import pandas as pd

In [13]:
z = np.zeros(8)
z

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
df = pd.read_csv('bmw.csv')

In [15]:
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0
...,...,...,...,...,...,...,...,...,...
10776,X3,2016,19000,Automatic,40818,Diesel,150,54.3,2.0
10777,5 Series,2016,14600,Automatic,42947,Diesel,125,60.1,2.0
10778,3 Series,2017,13100,Manual,25468,Petrol,200,42.8,2.0
10779,1 Series,2014,9930,Automatic,45000,Diesel,30,64.2,2.0
10780,X1,2017,15981,Automatic,59432,Diesel,125,57.6,2.0

In [21]:
pd.read_csv('bmw.csv',header = 0)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0
...,...,...,...,...,...,...,...,...,...
10776,X3,2016,19000,Automatic,40818,Diesel,150,54.3,2.0
10777,5 Series,2016,14600,Automatic,42947,Diesel,125,60.1,2.0
10778,3 Series,2017,13100,Manual,25468,Petrol,200,42.8,2.0
10779,1 Series,2014,9930,Automatic,45000,Diesel,30,64.2,2.0
10780,X1,2017,15981,Automatic,59432,Diesel,125,57.6,2.0

In [25]:
pd.read_csv('bmw.csv' ,index_col ='year')

          model  price transmission  mileage fuelType  tax   mpg  engineSize
year
2014   5 Series  11200    Automatic    67068   Diesel  125  57.6         2.0
2018   6 Series  27000    Automatic    14827   Petrol  145  42.8         2.0
2016   5 Series  16000    Automatic    62794   Diesel  160  51.4         3.0
2017   1 Series  12750    Automatic    26676   Diesel  145  72.4         1.5
2014   7 Series  14500    Automatic    39554   Diesel  160  50.4         3.0
...         ...    ...          ...      ...      ...  ...   ...         ...
2016         X3  19000    Automatic    40818   Diesel  150  54.3         2.0
2016   5 Series  14600    Automatic    42947   Diesel  125  60.1         2.0
2017   3 Series  13100       Manual    25468   Petrol  200  42.8         2.0
2014   1 Series   9930    Automatic    45000   Diesel   30  64.2         2.0
2017         X1  15981    Automatic    59432   Diesel  125  57.6         2.0

[10781 rows x 8 columns]

In [26]:
pd.read_csv('bmw.csv',usecols=['year','model','price','mileage','engineSize'])

           model  year  price  mileage  engineSize
0       5 Series  2014  11200    67068         2.0
1       6 Series  2018  27000    14827         2.0
2       5 Series  2016  16000    62794         3.0
3       1 Series  2017  12750    26676         1.5
4       7 Series  2014  14500    39554         3.0
...          ...   ...    ...      ...         ...
10776         X3  2016  19000    40818         2.0
10777   5 Series  2016  14600    42947         2.0
10778   3 Series  2017  13100    25468         2.0
10779   1 Series  2014   9930    45000         2.0
10780         X1  2017  15981    59432         2.0

[10781 rows x 5 columns]

In [32]:
pd.read_csv('bmw.csv',skiprows=[2,4])

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
2,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0
3,5 Series,2016,14900,Automatic,35309,Diesel,125,60.1,2.0
4,5 Series,2017,16000,Automatic,38538,Diesel,125,60.1,2.0
...,...,...,...,...,...,...,...,...,...
10774,X3,2016,19000,Automatic,40818,Diesel,150,54.3,2.0
10775,5 Series,2016,14600,Automatic,42947,Diesel,125,60.1,2.0
10776,3 Series,2017,13100,Manual,25468,Petrol,200,42.8,2.0
10777,1 Series,2014,9930,Automatic,45000,Diesel,30,64.2,2.0
10778,X1,2017,15981,Automatic,59432,Diesel,125,57.6,2.0

In [33]:
pd.read_csv('bmw.csv',nrows=10000)

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,5 Series,2014,11200,Automatic,67068,Diesel,125,57.6,2.0
1,6 Series,2018,27000,Automatic,14827,Petrol,145,42.8,2.0
2,5 Series,2016,16000,Automatic,62794,Diesel,160,51.4,3.0
3,1 Series,2017,12750,Automatic,26676,Diesel,145,72.4,1.5
4,7 Series,2014,14500,Automatic,39554,Diesel,160,50.4,3.0
...,...,...,...,...,...,...,...,...,...
9995,X3,2007,4990,Automatic,100000,Diesel,555,32.8,3.0
9996,3 Series,2012,11490,Automatic,89977,Diesel,125,60.1,2.0
9997,1 Series,2012,7000,Manual,68397,Diesel,30,62.8,2.0
9998,X3,2012,10800,Automatic,62335,Diesel,160,50.4,2.0
9999,X4,2015,21800,Automatic,26722,Diesel,205,47.9,3.0

In [34]:
pd.read_csv('bmw.csv').info()

<class 'pandas.DataFrame'>
RangeIndex: 10781 entries, 0 to 10780
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         10781 non-null  str
 1   year          10781 non-null  int64
 2   price         10781 non-null  int64
 3   transmission  10781 non-null  str
 4   mileage       10781 non-null  int64
 5   fuelType      10781 non-null  str
 6   tax           10781 non-null  int64
 7   mpg           10781 non-null  float64
 8   engineSize    10781 non-null  float64
dtypes: float64(2), int64(4), str(3)
memory usage: 758.2 KB

<class 'pandas.DataFrame'>
RangeIndex: 10781 entries, 0 to 10780
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         10781 non-null  str
 1   year          10781 non-null  int64
 2   price         10781 non-null  int64
 3   transmission  10781 non-null  str
 4   mileage       10781 non-null  int64
 5   fuelType      10781 non-null  str
 6   tax           10781 non-null  int64
 7   mpg           10781 non-null  float64
 8   engineSize    10781 non-null  float64
dtypes: float64(2), int64(4), str(3)
memory usage: 758.2 KB

In [45]:
pd.read_csv('bmw.csv',chunksize=5000)