**Column_Transformaton:-** It is a technique in which we tranform column from one form to another form

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [4]:
df.isna().sum() # we have 10 null values in the fever column

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [6]:
df.info() # here we have 4 columns categorical values present

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [7]:
# now we are spliting our data into train and test data set
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.3,random_state=42)

In [9]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(70, 5)
(30, 5)
(70,)
(30,)

**AAM ZINDGI**

In [10]:
# first we fill the missing values 
from sklearn.impute  import SimpleImputer

In [11]:
# we can impute like that first fit then transform never do on test data due 
# to this it causes data leakage
# si = SimpleImputer()
# si.fit(X_train[['fever']])
# si.fit(X_test[['fever']])
# X_train_fever = si.transform(X_train[['fever']])
# X_test_fever =si.transform(X_test[['fever']])
# X_train_fever

In [13]:
# here we give fit_tranform at same time
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])
X_test_fever = si.fit_transform(X_test[['fever']])
X_train_fever

array([[ 98.        ],
       [104.        ],
       [103.        ],
       [104.        ],
       [100.        ],
       [100.96721311],
       [104.        ],
       [102.        ],
       [102.        ],
       [103.        ],
       [104.        ],
       [102.        ],
       [100.96721311],
       [104.        ],
       [102.        ],
       [100.96721311],
       [ 99.        ],
       [100.96721311],
       [104.        ],
       [102.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [100.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [103.        ],
       [100.96721311],
       [ 98.        ],
       [ 99.        ],
       [ 99.        ],
       [101.        ],
       [ 99.        ],
       [101.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [103.        ],
       [100.96721311],
       [ 98.        ],
       [ 99.        ],
       [ 98.        ],
       [ 99.        ],
       [102.        ],
       [101.        ],
       [100.96721311],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [100.96721311],
       [100.        ],
       [100.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [100.96721311],
       [104.        ],
       [104.        ],
       [ 98.        ],
       [ 98.        ],
       [102.        ],
       [104.        ],
       [104.        ],
       [102.        ],
       [100.        ]])

In [ ]:
X_train.sample(5)

    age  gender  fever   cough       city
48   66    Male   99.0  Strong  Bangalore
89   46    Male  103.0  Strong  Bangalore
58   23    Male   98.0  Strong     Mumbai
61   81  Female   98.0  Strong     Mumbai
57   49  Female   99.0  Strong  Bangalore

In [ ]:
# we apply ordinal encodin on cough beacuse here is the realationship 
# b/w the data
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.fit_transform(X_test[['cough']])

In [ ]:
oe.categories_

[array(['Mild', 'Strong'], dtype=object)]

In [ ]:
# we apply one hot encoding in the gender and city 
ohe = OneHotEncoder()
# we apply ohe n-1
ohe = OneHotEncoder(
    drop='first',
    handle_unknown='ignore',
    sparse_output=False
)

In [ ]:
ohe.fit(X_train[['gender','city']])
X_train_city_gender = ohe.transform(X_train[['gender','city']])
X_test_city_gender = ohe.transform(X_test[['gender','city']])
X_train_city_gender.shape

(70, 4)

In [ ]:
# we are extracting age from the dataFrame
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

In [ ]:
# now we merge all the features aftear ecodng in one data frame
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_city_gender,X_train_cough),axis=1)

X_test_transformed =np.concatenate((X_test_age,X_test_fever,X_test_city_gender,X_test_fever),axis=1)

In [ ]:
# we convert numpy array  datafame usin pandas
X_train_transformed=pd.DataFrame(X_train_transformed)
X_train_transformed.sample(7)

       0      1    2    3    4    5    6
36  19.0  101.0  0.0  0.0  0.0  1.0  0.0
23  49.0  101.0  0.0  1.0  0.0  0.0  0.0
1   18.0  104.0  0.0  0.0  0.0  0.0  0.0
29  46.0  103.0  1.0  0.0  0.0  0.0  1.0
49   6.0  104.0  0.0  0.0  1.0  0.0  0.0
39  20.0  101.0  0.0  0.0  0.0  0.0  0.0
0   65.0   98.0  0.0  0.0  0.0  1.0  0.0

**MENTOS ZINDAGI**

In [ ]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
transformer = ColumnTransformer(transformers=[
    #(tranformer_name,tranformer_type,data's)
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [ ]:
X_train_encoded=transformer.fit_transform(X_train)
X_test_encoded=transformer.fit_transform(X_test)

In [ ]:
X_train_encoded = pd.DataFrame(X_train_encoded)
X_train_encoded.shape

(70, 7)

In [ ]:
X_train_encoded.head()

       0    1    2    3    4    5     6
0   98.0  0.0  0.0  0.0  0.0  1.0  65.0
1  104.0  0.0  0.0  0.0  0.0  0.0  18.0
2  103.0  0.0  0.0  0.0  0.0  0.0  16.0
3  104.0  0.0  1.0  0.0  1.0  0.0  16.0
4  100.0  0.0  1.0  0.0  1.0  0.0  27.0

In [ ]:
X_train_transformed.head()

      0      1    2    3    4    5    6
0  65.0   98.0  0.0  0.0  0.0  1.0  0.0
1  18.0  104.0  0.0  0.0  0.0  0.0  0.0
2  16.0  103.0  0.0  0.0  0.0  0.0  0.0
3  16.0  104.0  1.0  0.0  1.0  0.0  0.0
4  27.0  100.0  1.0  0.0  1.0  0.0  0.0

**COnclusion:-** if we do transformatio on the datarame without columnTransformer then then it is lots of time consuming and tedious .
if we apply columntransformer method then it is very easy to imlement